In [1]:
import numpy as np

In [5]:
my_list = [1, 2, 3]
arr = np.array(my_list) # 1dimentional array

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat) # number of brackets shows the number of dimentions 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2) 
# creating a numpy range array, 
# similar to range in python
# third argument - step size

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3) # how many zeroes

array([0., 0., 0.])

In [15]:
np.zeros((5,5)) #first number of rows, second number of columns. it is a tuple of dimentsions we want

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0,5,10) # it creates 10 evenly spaced arguments between 0 and 5. it creates ONE DIMENTIONAL array

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.eye(4) #idendity matrix, diagnal of 1 when every other argument is 0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5) # one dimentional array filled with specified number of arguments between 0 and 1 

array([0.967421  , 0.70134916, 0.26205588, 0.99196502, 0.17513702])

In [20]:
np.random.rand(5,5) # 2 dimensional 

array([[0.38223074, 0.91359987, 0.86748482, 0.95180101, 0.04337887],
       [0.3446513 , 0.95278198, 0.15626151, 0.8562195 , 0.93735026],
       [0.33682453, 0.19054433, 0.16565081, 0.15733124, 0.00820451],
       [0.63708667, 0.04914942, 0.96775612, 0.90586736, 0.03219769],
       [0.71010107, 0.19796728, 0.22508924, 0.88896786, 0.20219439]])

In [23]:
np.random.randn(2) # standard normal distribution centred around 0

array([ 0.34709129, -0.46112682])

In [25]:
np.random.randint(1,100,20) # 20 random integers between 1 and 100(100 is not included)

array([54, 85, 55, 91, 95, 94, 83, 80, 51, 48, 82, 86, 81, 33, 43, 54, 92,
        7, 17, 35])

In [26]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)

In [28]:
ranarr

array([24, 27, 31, 28, 32, 45, 28, 13,  4,  1])

In [30]:
arr.reshape(5,5) 
# reshape an array into new number of dimensions,
# rows and columns. we have to fill up the matix<!
# n row times n col equals num of elements!

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr.max()

45

In [34]:
ranarr.min()

1

In [35]:
ranarr.argmax() # index location of max arg, same with argmin()

5

In [36]:
arr.shape # this arr is 1d

(25,)

In [37]:
arr = arr.reshape(5,5)

In [38]:
arr.shape 

(5, 5)

In [39]:
arr.dtype

dtype('int64')

In [40]:
arr = np.arange(0,11)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[1:5] # same as slicing lists or strings

array([1, 2, 3, 4])

In [45]:
arr[0:5] = 1000

In [46]:
arr

array([1000, 1000, 1000, 1000, 1000,    5,    6,    7,    8,    9,   10])

In [48]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [49]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
arr_2d[0][0] # first row first column

5

In [52]:
arr_2d[1,2] # row comma column

30

In [53]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [54]:
#conditional selection

In [55]:
arr = np.arange(1,11)

In [56]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
bool_arr = arr > 5 # gives back an array of bolean values

In [62]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [63]:
arr[arr>6] # we can do it in one line like this   

array([ 7,  8,  9, 10])

In [66]:
arr_2d = np.arange(1,51).reshape(5,10)


In [67]:
arr_2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [68]:
# get 14-17,24-27,34-37
arr_2d[1:4,3:7]

array([[14, 15, 16, 17],
       [24, 25, 26, 27],
       [34, 35, 36, 37]])

In [69]:
# if we divide arr by arr and there is 0, it will create a nan,

In [71]:
np.sqrt(arr_2d) # creates squere root of every element in array

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
        4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558],
       [5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
        6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532],
       [6.40312424, 6.4807407 , 6.55743852, 6.63324958, 6.70820393,
        6.78232998, 6.8556546 , 6.92820323, 7.        , 7.07106781]])